"Challenge 04 - Curso Python #06"
firstEntry = input('Type something: ')
entryType = type(firstEntry)
#COMMENTED BELOW USE OLD FUNCTIONS
#print('{}, is of type {}'.format(firstEntry,entryType))
#print('Just spaces? {}'.format(firstEntry.isspace()))
#print('Is it numeric? {}'.format(firstEntry.isnumeric()))
#print('Is it alphabetic? {}'.format(firstEntry.isalpha()))
#print('Is it alphanumeric? {}'.format(firstEntry.isalnum()))
#print('Is it capital only? {}'.format(firstEntry.isupper()))
#print('Is it just lowercase? {}'.format(firstEntry.islower()))
#print('Is it capitalized? {0}'.format(firstEntry.istitle()))

print(f'{firstEntry}, is of type {entryType}')
print(f'Just spaces? {firstEntry.isspace()}')
print(f'Is it numeric? {firstEntry.isnumeric()}')
print(f'Is it alphabetic? {firstEntry.isalpha()}')
print(f'Is it alphanumeric? {firstEntry.isalnum()}')
print(f'Is it capital only? {firstEntry.isupper()}')
print(f'Is it just lowercase? {firstEntry.islower()}')
print(f'Is it capitalized? {firstEntry.istitle()}')
